# Generated by Django 5.0.4 on 2024-07-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maladie',
            name='tel',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
