# Generated by Django 5.0.4 on 2024-07-20 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_maladie_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichemedicale',
            name='maladie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_medicales', to='app.maladie'),
        ),
    ]
